name: On pull requests

on:
  pull_request:
    branches:
      - main

jobs:
  configure-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Configure env file
        run: |
          npx vercel --token ${{ secrets.VERCEL_TOKEN }} link --scope 'nelsonkenzotamashiros-projects' --project 'neo-news' -y
          npx vercel --token ${{ secrets.VERCEL_TOKEN }} pull --scope 'nelsonkenzotamashiros-projects' -y

  typecheck:
    runs-on: ubuntu-latest
    needs: configure-env  # This job depends on the configure-env job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Run Biome Check
        run: npm run typecheck

  build:
    runs-on: ubuntu-latest
    needs: configure-env  # This job depends on the configure-env job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build Next.js Application
        run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: configure-env  # This job depends on the configure-env job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Run Vitest
        run: npm run test